[General]
autoUpdateCheck=false
darkMode=ON
language=en
showOnboarding=false
enableTrayIcon=false
shuffleScreenKeyboard=true
transportPinReminder=false
useSystemFont=true
visualPrivacy=true
preferredTechnology=PCSC
; !!! should be disabled in production builds!!!
developerOptions=true
