# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have a packages directory, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "ausweisapp"
BBFILE_PATTERN_ausweisapp := "^${LAYERDIR}/"
BBFILE_PRIORITY_ausweisapp = "6"
LAYERSERIES_COMPAT_ausweisapp = "scarthgap"
LAYERDEPENDS_ausweisapp = "core openembedded-layer qt6-layer"
