[General]
autoUpdateCheck=false
darkMode=ON
language=en
showOnboarding=false
enableTrayIcon=false
shuffleScreenKeyboard=true
transportPinReminder=false
useSystemFont=true
visualPrivacy=true
preferredTechnology=SIMULATOR
selfauthTestUri=true
developerOptions=true
developerMode=true

[simulator]
enabled=true
basicReader=false
